version: '3.3'

services:
  webpack:
    build: .
    command: npm run start:webpack
    volumes:
      - ./src:/usr/src/app/src:cached
      - ./public/dist:/usr/src/app/public/dist:cached

  api:
    build: .
    command: npm run start:api
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URL=mongodb://admin:secret@mongo:27017
      - BSD_API_BASE_URL=https://markey.cp.bsd.net
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/src:cached
      - ./public/dist:/usr/src/app/public/dist:cached

  mongo:
    image: mongo:4
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    logging:
        driver: none
