const copy = {
  formLabels: {
    shareCode: 'Share code',
    shareCodeHelp: 'We suggest using a combination of your first + last name.',
    title: 'Title',
    subtitle: 'Share why your #StickingWithEd',
    background: 'Background',
    firstName: 'First name',
    lastName: 'Last name',
    zip: 'Zip',
    phone: 'Phone',
    email: 'Email',
  },
  idQuestions: {
    support: {
      label: 'Will you join me in voting to re-elect Ed Markey to the United States Senate on September 1st?',
      options: [
        'Definitely',
        'Probably',
        'Undecided',
        'Probably not',
        'Definitely not',
        'Too Young/Ineligible to Vote',
      ],
    },
    volunteer: {
      label: 'Will you volunteer with Team Markey?',
      options: [
        'Yes',
        'Maybe',
        'Later',
        'No',
      ],
    },
  },
  validations: {
    required: '*Required',
    nameLength: 'Must be less than 50 chars.',
    zipFormat: 'Invalid zip',
    phoneFormat: 'Invalid phone number',
    emailFormat: 'Invalid email',
    codeLength: 'Must be less than 50 chars.',
    codeFormat: 'Can only contain letters, numbers, dashes & underscores.',
  },
  homepage: {
    formTitle: 'Create your own Ed Markey supporter page',
    formSubtitle: 'Our grassroots campaign is powered by people like you who are connecting with family, friends, and neighbors about this important election. Complete the sections below to create your own personal supporter page and reach out to your network about why you’re a member of Team Markey!',
    customizeTitle: 'Customize your page',
    customizeSubtitle: `Fill out the sections below to personalize the title, description, and design of your supporter page to tell your network why you’re #StickingWithEd. Share your story of why you’re a member of this movement -- feel free to get creative!`,
    formButtonLabel: 'next',
    customizeButtonLabel: 'create',
    defaultSubtitle: 'Ed comes from a working family, and he’s fighting from the heart for the working class. Ed is running a people-powered campaign, and it’s up to us to help make sure he can keep fighting in the Senate for our shared progressive values. Let me know that you are with me, and help me reach my goal!',
    defaultTitle: `{{FIRST_NAME}} is #StickingWithEd because...`,
  },
  signupPage: {
    stepOneButtonLabel: 'Next',
    stepTwoButtonLabel: 'Submit',
    postSignupTitle: 'Thank you!',
    postSignupSubtitle: 'Next, keep up the momentum by sharing this link with your friends, family, and network, and help {{FIRST_NAME}} reach their goal! Or, make your own page and get everyone you know to join the fight.',
    postSignupCreateTitle: 'Make your own page',
    postSignupCreateSubtitle: 'Create your own supporter page and become a grassroots organizer for Ed. We’ll show you how!',
    postSignupCreateButtonLabel: 'Get started',
    modalTitle: `Here's how you can join ed's fight`,
    modalCopy: [
      `### Send your link far and wide`,
      `Share this page with your network to help us grow Team Markey! Your friends, family, neighbors, colleagues, roommates, classmates, Facebook friends, Twitter peeps, your Zoom hangout friends -- the sky's the limit, and we need to reach everyone.`,
      `### Relational organizing tips`,
      ` - Call 5 friends and ask them to fill out your link`,
      ` - Email your link to 50 people`,
      ` - Share it on your Facebook and other social media`,
      ` - Go through your contact list in your phone and text the link to at least 10 people!`,
      ' ',
      `### Volunteer with Team Markey`,
      `[Join the movement here](http://edmarkey.com/volunteer).`,
    ],
    modalCloseLabel: 'Okay, got it',
  },
  nav: {
    logoAlt: 'Ed Markey For Senate Logo',
    return: 'return to edmarkey.com',
    returnLink: 'https://www.edmarkey.com/',
    donate: 'donate',
    donateForm: 'https://secure.actblue.com/donate/ejm2020',
  },
  share: {
    facebook: 'Share on Facebook',
    twitter: 'Share on Twitter',
    email: 'Share via email',
    link: 'copy link',
  },
  genericError: 'Looks like we had an error, try again? If this continues to happen, please contact us https://www.edmarkey.com/contact-us/',
  politicalDiclaimer: 'PAID FOR BY THE MARKEY COMMITTEE',
  smsDisclaimer: 'By providing your cell phone number you consent to receive periodic campaign updates from the Markey Committee. Text HELP for help, STOP to end. Message & data rates may apply. https://www.edmarkey.com/privacy-policy/',
};

export default copy;
