name: API Integration Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Test
        run: docker-compose -f api-test.docker-compose.yml up --exit-code-from tests
